README.md

Readme is currently referencing the wrong repository + debug screenshot URL is wrong
Changed the repository reference + screenshot URL
Examine the readme

Changes readme repo references

---

example.py
opencopilot/application.py
opencopilot/ingest_data.py
opencopilot/settings.py
opencopilot/src/repository/documents/document_store.py

Add a global static variable for saving copilot name etc and initialize it on OpenCopilot() initialization

Framework data dir ingestion

---

README.md

please squash-and-merge when ready, tons of small commits here

Simplified readme

---

backend/settings.py
backend/src/domain/chat/results/get_llm.py
backend/template.env

We need user rate limiting
Added Helicone rate limit support
Set the rate limit policy using this [guide](https://docs.helicone.ai/features/advanced-usage/custom-rate-limits) and verify it's in effect.

Helicone rate limit support

---

opencopilot/application.py
opencopilot/domain/chat/utils.py
opencopilot/settings.py
tests/assets/e2e_example.py
tests/assets/example_without_run.py

Prompt initialization
Removes default prompt and adds required `prompt_file` init parameter.
Try creating a copilot

Adds prompt_file as mandatory

---

requirements.txt
setup.py

At the moment ingesting excel files fails because of a missing package
```
(venv) johannes@Johanness-MacBook-Pro opencopilot % python legal-copilot.py
{"asctime": "2023-08-22 12:27:03,772", "name": "backend-service", "levelname": "INFO", "message": "[Loading 7 files from data/.]"}
{"asctime": "2023-08-22 12:27:03,932", "name": "backend-service", "levelname": "INFO", "message": "Generated 1 document chunks from 1 documents"}
{"asctime": "2023-08-22 12:27:05,250", "name": "backend-service", "levelname": "INFO", "message": "Generated 10 document chunks from 10 documents"}
{"asctime": "2023-08-22 12:27:05,495", "name": "backend-service", "levelname": "INFO", "message": "Generated 10 document chunks from 10 documents"}
{"asctime": "2023-08-22 12:27:14,866", "name": "backend-service", …
```

Fix Excel files ingestion

---

README.md

- rewrite intro
- rm examples
- readme structure
- features & usecases
- fix links

README: intro, features, use cases

---

README.md

- stack image into README
- Update opencopilot overview

stack image

---

opencopilot/cli.py
opencopilot/scripts/eval_endtoend.py
opencopilot/scripts/eval_retrieval.py
opencopilot/utils/scripting.py

Eval scripts are broken
Fixed eval scripts - made `data_dir` parameter required
Run eval scripts

Fixes eval scripts

---

opencopilot/html/index.html

Bump JS library version to accommodate the new url format for conversation stream endpoint

Bump js library version

---

opencopilot/app.py

Open /ui in browser if cache.txt file not present

Open /ui in browser if cache file not present (ENG-400)

---

README.md

ENG-406 Update README first section

---

README.md

Changed docs structure - this changed the URLs which were out of date in the readme.

update links to docs

---

.github/workflows/e2e_test.yml
.github/workflows/e2e_test_full.yml
.github/workflows/e2e_test_jwt.yml
opencopilot/domain/chat/results/get_gpt_result_use_case.py
opencopilot/domain/chat/results/get_llm.py
setup.py

Master broken with previous PR
Reverted some OpenAI-related changes
Run CI tests

Fixes e2e tests

---

README.md

Updates readme to mention Llama 2 as possible LLM.

Adds LLama reference to `Quickstart`

---

requirements.txt

fixes https://github.com/opencopilotdev/opencopilot/security/dependabot/8

gitpython version

---

opencopilot/cli.py
opencopilot/utils/prompting.py

"Simplify prompt generation"
Added CLI prompt generation tool
run  `opencopilot prompt --help`

Prompt template generator (ENG-429)

---

examples/docker_deployment/docker/copilot/Dockerfile
opencopilot/analytics.py

Tested manually:
* locally - works the same as before
* on replit - works as intended
* in docker - works as intended
Commits
- fix LLM name setting bug; detect if we are in replit and set ID appropriately
- prefix for replit

Fixes analytics bug & replit identification (ENG-440)

---

opencopilot/domain/chat/models/local.py
opencopilot/domain/chat/on_user_message_streaming_use_case.py
opencopilot/domain/chat/results/get_gpt_result_use_case.py
opencopilot/domain/error_messages.py
opencopilot/domain/errors.py
opencopilot/service/error_responses.py
opencopilot/service/middleware/main_middleware.py

Adding clean error handling to LocalLLM calls.

Adds error handling to LocalLLM.

---

examples/coding_copilot/README.md
examples/coding_copilot/requirements.txt

Coding copilot missed the instructions on how to use - added.

Adds example on how to use coding copilot.

---

examples/custom_prompt_builder/copilot.py
examples/custom_prompt_builder/intents.py
examples/custom_prompt_builder/requirements.txt

`prompt_builder` feature needs an example implementation

Adds example implementation using `prompt_builder`

---

setup.py

PyPi was missing readme and project description.

Release v0.3.8 with documentation in PyPi.

---

.github/pull_request_template.md
examples/docker_deployment/docker-compose.yml
examples/docker_deployment/requirements.txt

Updates docker deployment setup. Removed the separate frontend container and uses the built in frontend that is hosted on copilot Rest API on `/ui`

Updates docker deployment setup.

---

.github/workflows/e2e_test_full.yml
opencopilot/domain/chat/entities.py
opencopilot/domain/chat/results/get_gpt_result_use_case.py
opencopilot/domain/chat/utils.py
opencopilot/domain/cli/cli_chat_use_case.py
opencopilot/routers/routes/chat_router.py
opencopilot/service/chat/chat_service.py
opencopilot/service/chat/chat_streaming_service.py
opencopilot/service/chat/chat_utils.py
opencopilot/service/chat/entities.py
tests/assets/e2e_example.py
tests/assets/e2e_example_data/data.txt
tests/e2e/test_backend_e2e_example.py
tests/unit/domain/chat/test_utils.py
tests/unit/service/chat/test_chat_service.py

Insert the task link or describe the problem you're solving

Adds message history to chat endpoint.

---

opencopilot/oss.py

Make sure OSS CLI model info includes:
- model
- system requirements
- license
- param count
- description
[* Related docs pr](https://github.com/opencopilotdev/docs/pull/24)

Adds more info to oss model table (ENG-395)
